# Generated by Django 3.1.6 on 2021-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='superstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('order_id', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField()),
                ('ship_date', models.DateTimeField()),
                ('ship_mode', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
                ('customer_name', models.TextField(max_length=25)),
                ('segment', models.TextField(max_length=25)),
                ('country', models.TextField(max_length=25)),
                ('city', models.TextField(max_length=25)),
                ('state', models.TextField(max_length=25)),
                ('postal_code', models.IntegerField()),
                ('region', models.TextField(max_length=25)),
                ('product_id', models.CharField(max_length=25)),
                ('category', models.TextField(max_length=25)),
                ('sub_category', models.TextField(max_length=25)),
                ('product_name', models.CharField(max_length=100)),
                ('sales', models.DecimalField(decimal_places=5, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
