# Generated by Django 3.1.6 on 2021-02-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superstore',
            name='row_id',
        ),
        migrations.AlterField(
            model_name='superstore',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
